# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-26 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdb',
            name='studpic',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to=b''),
        ),
    ]
