# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clanguage',
            fields=[
                ('isbn', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=200)),
                ('bookname', models.IntegerField()),
            ],
            options={
                'db_table': 'cdetails',
            },
        ),
    ]
