# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contactnumber', models.IntegerField()),
                ('course', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'myenquiry',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dateofexp', models.DateField()),
                ('readroomname', models.CharField(max_length=50)),
                ('sumexp', models.IntegerField()),
            ],
            options={
                'db_table': 'myexpense',
            },
        ),
    ]
